on: push

name: jira-todo

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Jira TODO
        uses: atlassian/gajira-todo@master
        with:
          project: GB
          issuetype: Task
          description: Created automatically via GitHub Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
